eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.29.40:8761/eureka
      
spring:
  application:
    name: CONFIG-PROD
